### ISSUE TITLE
Regular links don't work on mobile

### ISSUE THREAD

**Issue by Bargs** [runspired/ember-mobiletouch#29]
I don't know if this is an actual issue, or a misunderstanding on my part.

I have a couple of regular <a> elements in a template, e.g.:

`<a href="https://www.google.com/">Google</a>`

I'd like them to behave as normal links. This works fine on desktop if I add the `allow-click` class, but on mobile the click still gets busted by the GhostBuster. Is there any way to get these to work on mobile without setting up action helpers for tap, or is this a current limitation of the framework?

Thanks!

**Comment by runspired** [comment]
@Bargs this is a known issue with the 1.4 series that's affected by the ongoing refactor introducing `internalClick`.  Tests around the behavior of links (including external links) are currently being developed on the `develop` branch, and the next release in the 1.4 cycle should include a fix for this.

I believe it's currently possible for us to drop the GhostBuster entirely, letting all of these clicks bubble through `internalClick`, as hammer does not recognize ghost clicks as taps (it's bound to mousedown / mouseup behaviors).  I don't want to drop the buster without having more robust testing in place in case in introduces other unexpected behavior, but if you branch the latest master, comment out the buster, and it works correctly I'd love the feedback!

**Comment by Bargs** [comment]
Thanks for the info. I did as you suggested and commented out the buster. So far, so good. My use case isn't terribly complex, but swipes are working and regular link-to and action helpers seem to still work fine. The external links also work on mobile now.

I'll work off this version without the buster for awhile and let you know if I run into any weird issues. Let me know if there's anything specific you'd like me to test, I'd be happy to help.

**Comment by runspired** [comment]
This should be fixed in 1.4.7 and is now under test coverage.  If this remains an issue after upgrading, I'll reopen the issue.

**Comment by Bargs** [comment]
I updated to 1.4.7 but I'm still seeing the same issue.

It looks like the ghost buster is still preventing default browser behavior. The new tests only check for events on the view. Since the ghost buster is registered with the body element, it doesn't prevent these events from being triggered on the view, but it does prevent the default browser behavior. That's what it looks like to me at least.

**Comment by runspired** [comment]
Try the develop branch.

**Comment by Bargs** [comment]
Still no dice. I think the fastclick property is always undefined in the new conditional in the buster because it's using the native dom event object instead of the jquery event created in the event-dispatcher. 

Also, I just noticed that clicks on regular links in a desktop browser no longer work in 1.4.7 or develop (despite using the allow-click class). These events aren't getting busted in prevent-ghost-click.js, so perhaps there are two issues at play here?

**Comment by runspired** [comment]
I just added separate mobile/desktop tests and removed the click buster on develop.

**Comment by runspired** [comment]
I suspect this round of changes might affect the focus mechanism.  I'm adding tests for focus behavior tonight, so that will get cleaned up before I push 1.4.8.

**Comment by runspired** [comment]
I improved the tests for desktop vs mobile behavior and added tests for the focus mechanism.  I also improved the click busting story (far fewer rules to sort through, new docs coming).  Try out 1.4.8 and let me know how it goes.

**Comment by Bargs** [comment]
1.4.8 works great! External links are working on both mobile and desktop browsers. :thumbsup:

**Comment by Bargs** [comment]
This issue seems to be back again in version 1.4.10

**Comment by runspired** [comment]
Confirmed and affecting 2.0 build.

**Comment by theworkerant** [comment]
Any news here? I tried 1.4.8 without luck. @Bargs Did you still need to comment out ghost buster here?

**Comment by runspired** [comment]
@theworkerant working on it :)

**Comment by theworkerant** [comment]
Any workaround in the mean time?

**Comment by runspired** [comment]
does adding the class `needsclick` to the link work?

**Comment by theworkerant** [comment]
Nope, tried that and `allow-click`

**Comment by kbullaughey** [comment]
I think this has just been fixed on master (i.e., not the beta), and should make the next 1.4.x release. At least I can confirm it works when `allow-click` is set.

**Comment by Bargs** [comment]
I can confirm that this is working for me on 1.4.11
